/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author MSI
 */
public class PnlMoneda extends javax.swing.JPanel {

    /**
     * Creates new form PnlMoneda
     */
    public PnlMoneda() {
        initComponents();
    }

    public JButton getBtnNew() {
        return BtnNew;
    }

    public JTextField getTxtCordobas() {
        return TxtCordobas;
    }

    public JButton getBtnCalc() {
        return BtnCalc;
    }

    public JTextField getTxtDolares() {
        return TxtDolares;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BtnCalc = new javax.swing.JButton();
        BtnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCordobas = new javax.swing.JTextField();
        TxtDolares = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(157, 42));
        jPanel1.setPreferredSize(new java.awt.Dimension(157, 42));

        BtnCalc.setText("Calcular");
        BtnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCalc);

        BtnNew.setText("Nuevo");
        jPanel1.add(BtnNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(87, 90));
        jPanel2.setPreferredSize(new java.awt.Dimension(87, 90));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Dolares");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        jPanel2.add(TxtCordobas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 200;
        jPanel2.add(TxtDolares, gridBagConstraints);

        jLabel2.setText("Cordobas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel2, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalc;
    private javax.swing.JButton BtnNew;
    private javax.swing.JTextField TxtCordobas;
    private javax.swing.JTextField TxtDolares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
